version: '3'

services:
  nginx-gateway:
    image: nginx:1.21.5
    container_name: nginx-gateway
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8888:8081
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx
    networks:
      - CloudMind_net
    depends_on:
      - golang
#  CloudMind:
#      image: lyumikael/gomodd:v1.0.0 # if you "macOs intel" or "linux amd"
#      #image: lyumikael/go-modd-env:v1.0.0  # if you macOs m1
#      container_name: CloudMind
#      environment:
#        # 时区上海 - Timezone Shanghai
#        TZ: Asia/Shanghai
#        GOPROXY: https://goproxy.cn,direct
#      working_dir: /go/CloudMind
#      volumes:
#        - .:/go/CloudMind
#      privileged: true
#      restart: always
#      networks:
#        - CloudMind_net

    #前端api + 业务rpc - Front-end API + business RPC
  golang: # 自定义容器名称
    build:
      context: ./golang                  # 指定构建使用的 Dockerfile 文件
    environment: # 设置环境变量
      - TZ=Asia/Shanghai
    privileged: true
    volumes: # 设置挂载目录
      - ../CloudMind:/usr/src/code  # 引用 .env 配置中 CODE_PATH_HOST 变量，将宿主机上代码存放的目录挂载到容器中 /usr/src/code 目录
    ports: # 设置端口映射
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "9000:9000"
      - "9001:9001"
      - "9002:9002"
      - "9003:9003"
    stdin_open: true                     # 打开标准输入，可以接受外部输入
    tty: true
    networks:
      - CloudMind_net
    restart: always                      # 指定容器退出后的重启策略为始终重启
networks:
  CloudMind_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
